export {
    spec,
    type Awaitable,
    type Given,
    type Holds,
    type InputContext,
    type CollectedLaw,
    type LawDefinition,
    type MockDefinition,
    type MockExpectation,
    type MockHandler,
    type MockContext,
    type SpecBuilder,
    type SpecDefinition,
} from "./src/public/spec.ts";
